#!/usr/bin/env node

const program = require('commander');

program
  .arguments('<username> <email> [displayName]')
  .option('-c, --create', 'Create New User')
  .parse(process.argv);

console.log(program.username);
console.log(program.email);
console.log(program.displayName);
